export const POSTAGEM_LISTA_REQUEST = 'POSTAGEM_LISTA_REQUEST'
export const POSTAGEM_LISTA_SUCCESS ='POSTAGEM_LISTA_SUCCESS'
export const POSTAGEM_LISTA_FAIL = 'POSTAGEM_LISTA_FAIL'

export const POSTAGEM_DETALHES_REQUEST = 'POSTAGEM_DETALHES_REQUEST'
export const POSTAGEM_DETALHES_SUCCESS ='POSTAGEM_DETALHES_SUCCESS'
export const POSTAGEM_DETALHES_FAIL = 'POSTAGEM_DETALHES_FAIL'