//Constantes para exibir a lista de postagens
export const POSTAGEM_LISTA_REQUEST = 'POSTAGEM_LISTA_REQUEST'
export const POSTAGEM_LISTA_SUCCESS ='POSTAGEM_LISTA_SUCCESS'
export const POSTAGEM_LISTA_FAIL = 'POSTAGEM_LISTA_FAIL'

//Constantes para exibir os detalhes de uma postagem requisitada
export const POSTAGEM_DETALHES_REQUEST = 'POSTAGEM_DETALHES_REQUEST'
export const POSTAGEM_DETALHES_SUCCESS ='POSTAGEM_DETALHES_SUCCESS'
export const POSTAGEM_DETALHES_FAIL = 'POSTAGEM_DETALHES_FAIL'

//Constantes para um administrador excluir uma postagem 
export const POSTAGEM_DELETAR_REQUEST = 'POSTAGEM_DELETAR_REQUEST'
export const POSTAGEM_DELETAR_SUCCESS = 'POSTAGEM_DELETAR_SUCCESS'
export const POSTAGEM_DELETAR_FAIL = 'POSTAGEM_DELETAR_FAIL'

//Constantes para um administrador criar uma postagem
export const POSTAGEM_CRIAR_REQUEST = 'POSTAGEM_CRIAR_REQUEST'
export const POSTAGEM_CRIAR_SUCCESS = 'POSTAGEM_CRIAR_SUCCESS'
export const POSTAGEM_CRIAR_FAIL = 'POSTAGEM_CRIAR_FAIL'
export const POSTAGEM_CRIAR_RESET = 'POSTAGEM_CRIAR_RESET'

//Constantes para um administrador atualizar uma postagem
export const POSTAGEM_ATAULIZAR_REQUEST = 'POSTAGEM_ATAULIZAR_REQUEST'
export const POSTAGEM_ATUALIZAR_SUCCESS = 'POSTAGEM_ATUALIZAR_SUCCESS'
export const POSTAGEM_ATUALIZAR_FAIL = 'POSTAGEM_ATUALIZAR_FAIL'
export const POSTAGEM_ATUALIZAR_RESET = 'POSTAGEM_ATUALIZAR_RESET'

