//Constantes para logar e deslogar do sistema
export const USUARIO_LOGIN_REQUEST = 'USUARIO_LOGIN_REQUEST'
export const USUARIO_LOGIN_SUCCESS = 'USUARIO_LOGIN_SUCCESS'
export const USUARIO_LOGIN_FAIL = 'USUARIO_LOGIN_FAIL'
export const USUARIO_LOGOUT = 'USUARIO_LOGOUT'

//Constantes para registrar um usuário no sistema
export const USUARIO_REGISTER_REQUEST = 'USUARIO_REGISTER_REQUEST'
export const USUARIO_REGISTER_SUCCESS = 'USUARIO_REGISTER_SUCCESS'
export const USUARIO_REGISTER_FAIL = 'USUARIO_REGISTER_FAIL'

//Constante para mostrar os detalhes do usuário no sistema  
export const USUARIO_DETALHES_REQUEST = 'USUARIO_DETALHES_REQUEST'
export const USUARIO_DETALHES_SUCCESS = 'USUARIO_DETALHES_SUCCESS'
export const USUARIO_DETALHES_FAIL = 'USUARIO_DETALHES_FAIL'
export const USUARIO_DETALHES_RESET = 'USUARIO_DETALHES_RESET'

//Constante para atualizar os dethales do  perfil do usuário
export const USUARIO_ATUALIZAR_REQUEST = 'USUARIO_ATUALIZAR_REQUEST'
export const USUARIO_ATUALIZAR_SUCCESS = 'USUARIO_ATUALIZAR_SUCCESS'
export const USUARIO_ATUALIZAR_FAIL = 'USUARIO_ATUALIZAR_FAIL'
export const USUARIO_ATUALIZAR_RESET = 'USUARIO_ATUALIZAR_RESET'

//Constantes para o administrador listar os usuários
export const USUARIO_ADMIN_LISTAR_REQUEST = 'USUARIO_ADMIN_LISTAR_REQUEST'
export const USUARIO_ADMIN_LISTAR_SUCCESS = 'USUARIO_ADMIN_LISTAR_SUCCESS'
export const USUARIO_ADMIN_LISTAR_FAIL = 'USUARIO_ADMIN_LISTAR_FAIL'
export const USUARIO_ADMIN_LISTAR_RESET = 'USUARIO_ADMIN_LISTAR_RESET'

//Constantes para o administrador excluir usuários
export const USUARIO_ADMIN_DELETAR_REQUEST = 'USUARIO_ADMIN_DELETAR_REQUEST'
export const USUARIO_ADMIN_DELETAR_SUCCESS = 'USUARIO_ADMIN_DELETAR_REQUEST'
export const USUARIO_ADMIN_DELETAR_FAIL = 'USUARIO_ADMIN_DELETAR_REQUEST'